---
title: "01_compare_w_price_wright"
author: "Heather Wheeler"
date: "`r Sys.time()`"
output: html_document
---

```{r, echo=TRUE, message=FALSE, warning=FALSE}
packages<-c('ggplot2','dplyr','mada')
lapply(packages, library, character.only=T)
"%&%" = function(a,b) paste(a,b,sep="")
h2.dir <- '/Volumes/im-lab/nas40t2/Data/Annotations/heritability/'
```


```{r,fig.width=5,fig.height=5,warning=F,message=F}
gcta <- read.table('/Volumes/im-lab/nas40t2/hwheeler/cross-tissue/expArch_DGN-WB_imputedGTs/DGN-WB.h2.all.models_FHSfdr0.05.Chr1-22_globaleQTLOtherChr_reml-no-constrain.2015-12-13.txt',header=TRUE) %>% dplyr::select(gene,local.h2)
dim(gcta)
##get price h2 (custom-made human array containing 23,720 unique oligonucleotide probes, http://www.nature.com/nature/journal/v452/n7186/full/nature06758.html)
price <- read.table(h2.dir %&% "Alkes/h2all.txt",header=TRUE) %>% dplyr::rename(gene=gname)
dim(price)
wright <- read.table(h2.dir %&% "Fred/h2PB.txt",header=TRUE) %>% dplyr::rename(gene=gname)
dim(wright)
all<-full_join(gcta,price,by='gene')
all<-full_join(all,wright,by='gene')
#add GTEx whole blood
gtex <- read.table('/Volumes/im-lab/nas40t2/hwheeler/cross-tissue/GTEx.TW.WholeBlood.h2.all.models_FHSfdr0.05.Chr1-22_globaleQTLOtherChr_reml-no-constrain.2015-12-14.txt',header=T) %>% mutate(gtexWB=local.h2) %>% dplyr::select(gene,gtexWB)
all<-full_join(all,gtex,by='gene')
dim(all)
nona <- all[complete.cases(all),]
dim(nona)
#dgn v. gtex whole blood
ggplot(nona,aes(x=local.h2,y=gtexWB))+geom_point(alpha=1/4)+geom_smooth()+theme_bw()+coord_cartesian(ylim=c(-0.15,1.02))
res<-cor.test(nona$local.h2,nona$gtexWB,method='s')
CIrho(res$estimate,length(nona$local.h2))
#dgn v. price blood
ggplot(nona,aes(x=local.h2,y=h2bloodcis))+geom_point(alpha=1/4)+geom_smooth()+theme_bw()
res<-cor.test(nona$local.h2,nona$h2bloodcis,method='s')
CIrho(res$estimate,length(nona$local.h2))
#dgn v. wright peripheral blood
ggplot(nona,aes(x=local.h2,y=h2PB))+geom_point(alpha=1/4)+geom_smooth()+theme_bw()
res<-cor.test(nona$local.h2,nona$h2PB,method='s')
CIrho(res$estimate,length(nona$local.h2))
#wright v. price blood
ggplot(nona,aes(x=h2PB,y=h2bloodcis))+geom_point(alpha=1/4)+geom_smooth()+theme_bw()
res<-cor.test(nona$h2PB,nona$h2bloodcis,method='s')
CIrho(res$estimate,length(nona$local.h2))
```

###plot all 3 blood
```{r}
nona <- all[complete.cases(all),]
dim(nona)
#dgn v. price blood, color by wright
ggplot(nona,aes(x=local.h2,y=h2bloodcis,col=h2PB))+geom_point()+geom_smooth()+theme_bw()+ scale_colour_gradient(low="pink",high="blue")
#dgn v. wright peripheral blood, color by price
ggplot(nona,aes(x=local.h2,y=h2PB,col=h2bloodcis))+geom_point()+geom_smooth()+theme_bw()+ scale_colour_gradient(low="pink",high="blue")
#wright v. price blood, color by dgn
ggplot(nona,aes(x=h2PB,y=h2bloodcis,col=local.h2))+geom_point()+geom_smooth()+theme_bw()+ scale_colour_gradient(low="pink",high="blue")
```

###cor tables
```{r}
round(cor(all[,-1],use='pairwise.complete.obs',method="s"),3)
#Blood only
allblood <- dplyr::mutate(all,dgnWB=local.h2,Price=h2bloodcis,Wright=h2PB) %>% dplyr::select(dgnWB,gtexWB,Price,Wright)
#Pearson
round(cor(allblood,use='pairwise.complete.obs'),3)
#Spearman
round(cor(allblood,use='pairwise.complete.obs',method="s"),3)
```

###cor tables - intersection of the 4 whole blood studies
```{r}
dim(nona)
round(cor(nona[,-1],use='pairwise.complete.obs',method="s"),3)
#Blood only
allblood <- dplyr::mutate(nona,dgnWB=local.h2,Price=h2bloodcis,Wright=h2PB) %>% dplyr::select(dgnWB,gtexWB,Price,Wright)
#Pearson
round(cor(allblood,use='pairwise.complete.obs'),3)
#Spearman
round(cor(allblood,use='pairwise.complete.obs',method="s"),3)
```